# Generated by Django 5.2 on 2025-04-18 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description_event_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
